# Generated by Django 3.2.6 on 2021-11-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='baptized',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('I', 'Self Supporting'), ('C', 'Supported Church')], default='I', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='church_elder_first_name',
            field=models.CharField(default='ok', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='church_elder_last_name',
            field=models.CharField(default='ok', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='conference_name',
            field=models.CharField(default='ok', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='contact_assistant_email',
            field=models.EmailField(default='afasdf@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='contact_assistant_name',
            field=models.CharField(default='ok', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='field_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='home_church_email',
            field=models.EmailField(default='aaf@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='home_church_location',
            field=models.CharField(default='asdf', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='home_church_name',
            field=models.TextField(default='asf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='home_church_phone_numbers',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_minister',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_ministry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='adf', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(default='adf', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_numbers',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='position_church',
            field=models.CharField(default='deacon', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
