# Generated by Django 3.2.9 on 2022-02-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mpesa_mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
