# Generated by Django 3.2.9 on 2022-02-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_mpesa_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mpesa_mobile_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
