# Generated by Django 3.2.9 on 2022-02-04 11:55

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_mpesa_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
