# Generated by Django 3.2.9 on 2022-01-11 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("socialaccount", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="socialaccount",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="socialtoken",
            unique_together={("app", "account")},
        ),
        migrations.AlterUniqueTogether(
            name="socialaccount",
            unique_together={("provider", "uid")},
        ),
    ]
