# Generated by Django 3.2.6 on 2021-11-01 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evangelism', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ministry',
            name='church_elder_first_name',
        ),
        migrations.RemoveField(
            model_name='ministry',
            name='church_elder_last_name',
        ),
        migrations.RemoveField(
            model_name='ministry',
            name='home_church_email',
        ),
        migrations.RemoveField(
            model_name='ministry',
            name='home_church_location',
        ),
        migrations.RemoveField(
            model_name='ministry',
            name='home_church_name',
        ),
        migrations.RemoveField(
            model_name='ministry',
            name='home_church_phone_numbers',
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='minister',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='minister',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ministry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
