# Generated by Django 3.2.6 on 2021-11-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evangelism', '0002_auto_20211101_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='church_elder_first_name',
            new_name='church_elder_name',
        ),
        migrations.RenameField(
            model_name='minister',
            old_name='church_elder_first_name',
            new_name='church_elder_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='church_elder_last_name',
        ),
        migrations.RemoveField(
            model_name='minister',
            name='church_elder_last_name',
        ),
        migrations.AddField(
            model_name='member',
            name='church_elder_email',
            field=models.EmailField(default='awer@gmail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='asvc@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='minister',
            name='church_elder_email',
            field=models.EmailField(default='aewr@gmail.com', max_length=50),
            preserve_default=False,
        ),
    ]
