# Generated by Django 3.2.9 on 2022-01-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evangelism', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password2',
            field=models.CharField(default='admin', max_length=1024, verbose_name='Confirm Password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minister',
            name='password2',
            field=models.CharField(default='admin', max_length=1024, verbose_name='Confirm Password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ministry',
            name='password2',
            field=models.CharField(default='admin', max_length=1024, verbose_name='Confirm Password'),
            preserve_default=False,
        ),
    ]
