# Generated by Django 3.2.6 on 2021-11-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evangelism', '0003_auto_20211101_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minister',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='minister',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='minister',
            name='other_names',
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default='password', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minister',
            name='password',
            field=models.CharField(default='password', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ministry',
            name='password',
            field=models.CharField(default='password', max_length=1024),
            preserve_default=False,
        ),
    ]
