# Generated by Django 3.2.6 on 2021-11-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evangelism', '0004_auto_20211101_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='email',
            field=models.EmailField(default='awera@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
