# Generated by Django 3.2.9 on 2022-02-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="channel",
            name="ttl",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The number of minutes a channel can be cached before refreshing.",
                null=True,
                verbose_name="TTL",
            ),
        ),
    ]
